name: todo_list_app
description: To do list application.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_slidable: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.27.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "icons/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
  - family: Jost
    fonts:
      - asset: lib/styles/fonts/Jost.ttf